# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial32"

  config.vm.define "node1" do |node1|

    node1.vm.hostname = 'node1'
    node1.vm.network "private_network", ip: "192.168.100.10"
  end

  config.vm.define "node2" do |node2|

    node2.vm.hostname = 'node2'
    node2.vm.network "private_network", ip: "192.168.100.20"
  end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

end
